# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Instrument.create(name: "Piano")
Instrument.create(name: "Keyboard")
Instrument.create(name: "Guitar")
Instrument.create(name: "Electric Guitar")
Instrument.create(name: "Banjo")
Instrument.create(name: "Bass")
Instrument.create(name: "Contrabass")
Instrument.create(name: "Violin")
Instrument.create(name: "Violoncello")
Instrument.create(name: "Cello")
Instrument.create(name: "Harp")
Instrument.create(name: "Horn")
Instrument.create(name: "Trumpet")
Instrument.create(name: "Trombone")
Instrument.create(name: "Tuba")
Instrument.create(name: "Saxophone")
Instrument.create(name: "Flute")
Instrument.create(name: "Clarinet")
Instrument.create(name: "Oboe")
Instrument.create(name: "Timpani")
Instrument.create(name: "Percussion")
Instrument.create(name: "Drums")
Instrument.create(name: "Cymbals")
Instrument.create(name: "Vocal")
