# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Instrument.create(instrument: "Piano")
Instrument.create(instrument: "Keyboard")
Instrument.create(instrument: "Guitar")
Instrument.create(instrument: "Electric Guitar")
Instrument.create(instrument: "Banjo")
Instrument.create(instrument: "Bass")
Instrument.create(instrument: "Contrabass")
Instrument.create(instrument: "Violin")
Instrument.create(instrument: "Violoncello")
Instrument.create(instrument: "Cello")
Instrument.create(instrument: "Harp")
Instrument.create(instrument: "Horn")
Instrument.create(instrument: "Trumpet")
Instrument.create(instrument: "Trombone")
Instrument.create(instrument: "Tuba")
Instrument.create(instrument: "Saxophone")
Instrument.create(instrument: "Flute")
Instrument.create(instrument: "Clarinet")
Instrument.create(instrument: "Oboe")
Instrument.create(instrument: "Timpani")
Instrument.create(instrument: "Percussion")
Instrument.create(instrument: "Drums")
Instrument.create(instrument: "Cymbals")
Instrument.create(instrument: "Vocal")
